version: "3.8"
services:
  deno_graphql:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./.env:/app/.env
      - ./scripts.json:/app/scripts.json
      - ./src:/app/src
